#!/usr/bin/env php
<?php

declare(strict_types=1);

namespace AskNicely\BPro;

use Symfony\Component\Console\Application;

require_once __DIR__ . '/../vendor/autoload.php';

$app = new Application();
$app->add(new GetJobCommand());
$app->run();
